/*
* @Description:
* @Author:	Geordi Guo 
* @Email:	Geordi.Guo@igt.com
* @Date:	2019-07-01 09:50:16
* @Last Modified by:	Geordi Guo
* @Last Modified time:	2019-11-11 15:02:59
*/
define(function module(){

	function LittleGreenMenGameEvent(sourceObject, name){
		this.sourceObject = sourceObject;
		this.name = name;
	}
	LittleGreenMenGameEvent.eventIDs = {
		AUDIODIALOG_CLOSED:'LITTLEGREENMENGAMEEVENT_AUDIODIALOG_CLOSED',
		INNERPAYTABLEBTN_CLICKED: "LITTLEGREENMENGAMEEVENT_INNERPAYTABLEBTNCLICKED",
		INNERPAYTABLE_CLOSED:"LITTLEGREENMENGAMEEVENT_INNERPAYTABLECLOSED",
		TUTORIAL_SHOW: "LITTLEGREENMENGAMEEVENT_TUTORIAL_SHOW",
		TUTORIAL_CLOSED: "LITTLEGREENMENGAMEEVENT_TUTORIAL_CLOSED",
		PLANET_FIRE:'LITTLEGREENMENGAMEEVENT_PLANET_FIRE',
		UFONAVY_SPACESHIP_FIRE:"LITTLEGREENMENGAMEEVENT_UFONAVY_SPACESHIP_FIRE",
		UFONAVY_METEORITE_FIRE:"LITTLEGREENMENGAMEEVENT_UFONAVY_METEORITE_FIRE",
		PRICETABLE_FIGURE_UPDATE: "LITTLEGREENMENGAMEEVENT_PRICETABLE_FIGURE_UPDATE",
		SINGLE_SYMBOL_WIN_EXPLOSION_COMPLETE:"LITTLEGREENMENGAMEEVENT_SINGLE_SYMBOL_WIN_EXPLOSION_COMPLETE",
		REELS_REACTORDROP_COMPLETE: "LITTLEGREENMENGAMEEVENT_REELS_REACTORDROP_COMPLETE",
		METER_UPDATE_WINNING:"LITTLEGREENMENGAMEEVENT_METER_UPDATE_WINNING",
		METER_ADD_INSTANTWIN_WINNING:"LITTLEGREENMENGAMEEVENT_METER_ADD_INSTANTWIN_WINNING",
		BASEGAME_ET_FADEOUTCOMPLETED:"LITTLEGREENMENGAMEEVENT_BASEGAME_ET_FADEOUTCOMPLETED",
		FADEOUT_PRIZEDETAILS:"LITTLEGREENMENGAMEEVENT_BASEGAME_FADEOUT_PRIZEDETAILS",
		PRESSED_PRIZEDETAILS:"LITTLEGREENMENGAMEEVENT_BASEGAME_PRIZEDETAILS_PRESSED",
		MOUSE_OVER_PRIZEDETAILS:"LITTLEGREENMENGAMEEVENT_BASEGAME_PRIZEDETAILS_MOUSE_OVER",
		MOUSE_OUT_PRIZEDETAILS:"LITTLEGREENMENGAMEEVENT_BASEGAME_PRIZEDETAILS_MOUSE_OUT",

		STANDARD_BONUS_ENTRE_TRANSITION_COMPLETE:"LITTLEGREENMENGAMEEVENT_STANDARD_BONUS_ENTRE_TRANSITION_COMPLETE",
		STANDARD_BONUS_EXIT_TRANSITION_COMPLETE: "LITTLEGREENMENGAMEEVENT_STANDARD_BONUS_EXIT_TRANSITION_COMPLETE",
		STANDARD_BONUS_ENTRE_TRANSITION_START:"LITTLEGREENMENGAMEEVENT_STANDARD_BONUS_ENTRE_TRANSITION_START",
		STANDARD_BONUS_ALL_REELS_STOPPED: 'LITTLEGREENMENGAMEEVENT_STANDARD_BONUS_ALL_REELS_STOPPED',
		STANDARD_BONUS_ALL_WIN_SEQUENCE_COMPLETED:"LITTLEGREENMENGAMEEVENT_STANDARD_BONUS_ALL_WIN_SEQUENCE_COMPLETED",
		STANDARD_BONUS_EXIT_TRANSITION_START: "LITTLEGREENMENGAMEEVENT_STANDARD_BONUS_EXIT_TRANSITION_START",
		STANDARD_BONUS_UFO_HIGHLIGHT_COMPLETE:"LITTLEGREENMENGAMEEVENT_STANDARD_BONUS_UFO_HIGHLIGHT_COMPLETE",
		STANDARD_BONUS_GO_BUTTON_CLICKED:"LITTLEGREENMENGAMEEVENT_STANDARD_BONUS_GO_BUTTON_CLICKED",

		ACTION_BONUS_ENTRE_TRANSITION_START:"LITTLEGREENMENGAMEEVENT_ACTION_BONUS_ENTRE_TRANSITION_START",
		ACTION_BONUS_ENTRE_TRANSITION_COMPLETE:"LITTLEGREENMENGAMEEVENT_ACTION_BONUS_ENTRE_TRANSITION_COMPLETE",
		ACTION_BONUS_BULLET_LOADING_COMPLETE:"LITTLEGREENMENGAMEEVENT_ACTION_BONUS_BULLET_LOADING_COMPLETE",
	};
	Object.freeze(LittleGreenMenGameEvent.eventIDs);
	return LittleGreenMenGameEvent;
});
